version: '3'
services:
  visit:
    container_name: visit
    build:
      context: .
    depends_on:
      - redis
    links:
      - redis
    ports:
      - "3000:3000"
    environment:
      - REDIS_URL=redis://redis
  redis:
    image: redis:latest
    expose:
      - "6379"
